### ISSUE TITLE
Issue#1 - Proposal February 2018 Deliverable's

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#1]
It is suggested that EEA should focus in the delivery of these items by end of February 2018:

## Phase 1

*  **EntEth v1.0 Specifications**
      * A technical description of what is currently available on EEA "stock".
      * Description of functions and interfaces.
      * Indicate what is in and out of scope.

* **EEA Standardization Process Engagement**
     * This is the EEA Development Process. It sets the rules of engagement for the creation of any document defined and approved by EEA.
     * It is based on the "Specifications White Paper" and EEP GitHub repository.

* **Technical Requirements**
     * Get ready EEA Banking Requirements to be included in **EntEth v1.1 Specifications**.

**Comment by chaals** [comment]
Archiving this repository. For more information see https://entethalliance.org
