### ISSUE TITLE
EEP States

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#10]
Suggestion:
![image](https://user-images.githubusercontent.com/3258579/33243289-1721de94-d298-11e7-9db2-7c76101a25bc.png)

Working Groups repositories in GitHub should contain folders to match these EEP States:

## States/Folders Controlled by Working Groups (WG)
- **Draft**
   * Contains documents under Working Group development.
- **Withdrawn**
   * Contains documents that have been **withdrawn** by the corresponding Working Group.
- **Deferred**
   * Contains documents that have been placed in **deferred** by the Working Group.

## States/Folders Controlled by the Technical Steering Committee
- **Accepted**
   * Contains documents that have been **Agreed** or **Accepted** by the Technical Steering Committee (TSC)
- **Rejected**
   * Contains documents that have been **Rejected** by the TSC
- **Final**
   * Contains documents that have been **Finally Approved** by the TSC.
- **Replaced**
   * Contains documents that have been replaced by new documents.

**Comment by chaals** [comment]
Archiving this repository. For more information see https://entethalliance.org
