### ISSUE TITLE
Attendance to EEA Quorum Summit - New York (12th -14th Feb)

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#11]
Please register here your attendance indicating if you will be attending the meeting in person or remotely.
If it is in person, then indicate your name and company

**Comment by jpradocueva** [comment]
Joaquin Prado, EEA, I will attend in person.

**Comment by dhyansraj** [comment]
Dhyan Raj, Synechron, I will attend in person

**Comment by marleyg** [comment]
I will attend in person.  Marley Gray from Microsoft

**Comment by drinkcoffee** [comment]
Peter Robinson from ConsenSys. I will attend, possibly remote, possibly in person

**Comment by coeniebeyers** [comment]
Coenie Beyers from ConsenSys, I might attend remotely

**Comment by rynobey** [comment]
Ryno Beyers, ConsenSys, possibly attending remotely.

**Comment by ashfaq-shaik** [comment]
Ashfaq Shaik, Broadridge. Will attend in person.

**Comment by hironohata** [comment]
I will attend remotely.

**Comment by kseshak** [comment]
I will attend in person on 12th. Remote on 13th/14th
Please get in contact with @jpradocueva we need your email address.

**Comment by modernity** [comment]
Alex Liu and Chang-Wu Chen of AMIS

**Comment by conor10** [comment]
I will attend in person.

**Comment by ClifBarber** [comment]
Clif Barber will attend this meeting in person.

**Comment by grantnoble** [comment]
Grant Noble, ConsenSys, I will attend in person.

**Comment by rojotek** [comment]
Rob Dawson, Consensys will attend in person.

**Comment by shawndouglass** [comment]
Shawn Douglass, Amberdata will attend in person.

**Comment by tongtongg** [comment]
Tongtong Gong, Amberdata will attend in person.

**Comment by patrickmn** [comment]
Patrick Nielsen in person

**Comment by knowfn** [comment]
I will attend in person

**Comment by sbakshi007** [comment]
Sanjay from Intel will join in person

**Comment by jonathanbmorley** [comment]
Jonathan from CME will attend in person.

**Comment by dhh2106** [comment]
Daniel Heyman from ConsenSys will attend in person

**Comment by A-Joshi** [comment]
Amit Joshi from IHS Markit will attend in person.

**Comment by ronres** [comment]
Ron Resnick, Exec Dir of EEA will attend in person

**Comment by caleteeter** [comment]
I will be there in person, Cale Teeter from Microsoft

**Comment by kjameslubin** [comment]
I will attend in person and remotely, Kieren James-Lubin from BlockApps

**Comment by JoelSkerlong** [comment]
Joseph Lubin will attend remotely.

**Comment by tylobban** [comment]
I’ll attend in person

**Comment by tomwillis1** [comment]
tom willis from Intel will attend in person

**Comment by kriskamini** [comment]
Jeremy Millar will attend in person, from 12-14th Feb

**Comment by hironohata** [comment]
Hiro Nohata will attend remotely.

**Comment by NA714** [comment]
Niv Aviram, ConsenSys, will attend in person

**Comment by JasonRBC** [comment]
Jason Dodokin from RBC will attend remotely

**Comment by jimthematrix** [comment]
Jim Zhang, ConsenSys, in person

**Comment by reach2rb** [comment]
Attending in person.  Ramesh Babu from Wipro.

**Comment by peterr124** [comment]
Peter Rutgers, ING, attending in person

**Comment by GuillaumeDechaux** [comment]
Guillaume DECHAUX, TQ, attending remotely

**Comment by clarkathompson** [comment]
Clark Thompson Consensys attending

**Comment by naokitaniguchi** [comment]
Naoki Taniguchi, MUFG, attending in person.

**Comment by henrywj** [comment]
I will attend remotely

**Comment by mundipf** [comment]
Sascha Mundstein, Pfizer. Will attend remotely.

**Comment by ArtKorenyuk** [comment]
Artem Korenyuk -  in person

**Comment by changwu-tw** [comment]
Chang-Wu Chen, AMIS, will attend in person

**Comment by Joshua-Wipro** [comment]
Joshua Q. Israel Satten, Blockchain Partner-NA @ Wipro, shall attendeth in personeth...

"Brooklyn, top of the food chain." - Mike Tyson

**Comment by fish-sammy** [comment]
Sammy Liu, Scotiabank, will attend in person

**Comment by jpradocueva** [comment]
REGISTRATION IS NOW CLOSED.

**Comment by jpradocueva** [comment]
Didier LE FLOCHDidier LE FLOCH
Trade Quorum
Attending in person.

**Comment by hitarshi** [comment]
Hitarshi Buch - Wipro, - I will join remotely.

**Comment by jamshidh** [comment]
James Hormuzdiar, BlockApps, will attend in person
@jamshidh please note that the registration is already closed.

**Comment by prototypo** [comment]
David Hyland-Wood of ConsenSys will attend remotely.
