### ISSUE TITLE
Issue#2 - EEA Standardization Process Engagement

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#2]
# Proposal baseline documents:
 * Specifications White Paper
 * EEP GitHub 

# Process Proposal
 * [Issue #3 EEA Overall Process](https://github.com/EntEthAlliance/EEA_Process/issues/3)
 * [Issue #4 EEP Process](https://github.com/EntEthAlliance/EEA_Process/issues/4)
 * [Issue #5 Use Case Process](https://github.com/EntEthAlliance/EEA_Process/issues/5)

**Comment by chaals** [comment]
Archiving this repository. For more information see https://entethalliance.org
