### ISSUE TITLE
Issue #4 - EEP Process Proposal

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#4]
It is suggested to follow up this process for the creation of EEPs.
![image](https://user-images.githubusercontent.com/3258579/33243328-d562898a-d298-11e7-8cf1-66504f14176b.png)

# What is an EEP
 * EPP is a markdown document that describes any input into EEA: e.g. use cases, requirements, proposal for a new Working Group (WG), new features, process changes, guidelines, templates, etc.
 * Similar type of document & process as Ethereum Improvement Proposal (EIP) of Ethereum Foundation.

 # Name schema (EEP & Issue)
 * Issue name: [Proposal-title]-{WG}-#IssueNumber.
 * EEP name: [IssueNumber]-{WG}-[title].md.

# Content
 * Be clear an concise what you want to do with the introduction of the new enhance or feature.
 * Link the EEP, once created, to the Issue “IssueNumber” that trigger the EEP.

# Author
 * She/he is the champion for the Issue and the EEP.
* Responsible for building consensus with the community and writing the EEP doc.

**Comment by jpradocueva** [comment]
It was suggested that each Working Group (WG) should have its own Repository. In that case we may need to centralize the Templates in a repository also.

**Comment by chaals** [comment]
Archiving this repository. For more information see https://entethalliance.org
