### ISSUE TITLE
Attendance to EEA Quorum WG Summit - London (11 - 12 Dec)

### ISSUE THREAD

**Issue by jpradocueva** [EntEthAlliance/EEA_Terms-of-Use#8]
People attending in person:
* Jack Gavigan, (Zcash),
* Shawn Douglas, ?
* Ryno Beyers, (ConsenSys),
* Dan Heyman, (ConsenSys),
* Ben Edgington, (ConsenSys),
* Marley Gray,  ?
* Jonathan Morley, (CME Group),
* Martin Michlmayr, (Clearmatics), (Tuesday only)
* George Ornbo, (Clearmatics), (Monday only),
* Jeremy Cousins, (Clearmatics), (Monday only),
* Ian Cusden, (UBS),
* Jeremy Millar, (ConsenSys),
* Kristelle Kamini, (ConsenSys),
* Suresh Shetty, (JPMorgan),
* Samer Falah, (JPMorgan),
* Tyrone Lobban, (JPMorgan),
* Patrick Nielson, (JPMorgan),
* Alex Liu, (AMIS),
* Peter Rutgers, (ING)
* Peter Broadhurst, (ConsenSys),
* John Whelan, (Santander),
* Przemek Siemion, (Santander),
* Conor Svensson, (Blk)
* Joaquin Prado, (EEA)

**Comment by jpradocueva** [comment]
Joaquin Prado, EEA, in person +1

**Comment by drinkcoffee** [comment]
I (Peter Robinson, ConsenSys) will be attending remotely

**Comment by lizamf** [comment]
Joseph Lubin will be attending remotely.

**Comment by jackgavigan** [comment]
I will attend in person. (Jack Gavigan, Zcash)

**Comment by bretthenderson** [comment]
Brett Henderson (ConsenSys) attending remotely

**Comment by shawndouglass** [comment]
Looking forward to attending in person
@shawndouglass, can you please state your company? Thanks

**Comment by A-Joshi** [comment]
I will attend remotely

**Comment by kseshak** [comment]
I will attend Remotely - Kishore Seshagiri (Broadridge)

**Comment by coeniebeyers** [comment]
I will attend remotely (Coenie Beyers from ConsenSys)

**Comment by rynobey** [comment]
Ryno Beyers (ConsenSys) - I will be there in person

**Comment by dhh2106** [comment]
I will attend in person (Dan Heyman from ConsenSys)

**Comment by benjaminion** [comment]
Ben Edgington (ConsenSys), attending in person.

**Comment by smart-t** [comment]
I will be attending Remotely (maybe in person)

**Comment by marleyg** [comment]
I will be attending in person.
@marleyg  could you please state your company? Thanks

@jpradocueva Microsoft

**Comment by jonathanbmorley** [comment]
Jonathan Morley (CME Group) will attend in person.

**Comment by hironohata** [comment]
Nohata will  attend remotely.

**Comment by tbm** [comment]
I will attend in person on Tuesday. (Martin Michlmayr from Clearmatics)

**Comment by shapeshed** [comment]
I will attend in person on Monday (George Ornbo from Clearmatics)

**Comment by jay-cousins** [comment]
I will attend in person on Monday (Jeremy Cousins from Clearmatics)

**Comment by magooster** [comment]
I will attend in person (Ian Cusden from UBS)

**Comment by kriskamini** [comment]
Jeremy Millar, Kristelle Kamini from ConsenSys London, attending in person on BOTH days :)

**Comment by shalusure** [comment]
I will attend in person (Suresh Shetty from JPMorgan) ..... Sam Falah, Tyrone Lobban and Patrick Nielson will be attending as well

**Comment by modernity** [comment]
I will be attending in person (Alex Liu from AMIS)

**Comment by peterr124** [comment]
Peter Rutgers (ING), attending in person

**Comment by peterbroadhurst** [comment]
Peter Broadhurst from ConsenSys (newly joined) - attending in person

**Comment by jwhelan72** [comment]
John Whelan (Santander) - attending in person
Przemek Siemion (Santander) - attending in person

**Comment by jonathanbmorley** [comment]
Leaving a new comment so my edit is picked up. Jonathan Morley (CME Group) be attending in person now.

**Comment by robertusr** [comment]
Robert Coote (ConsenSys) attending remotely.

**Comment by rojotek** [comment]
Rob Dawson (ConsenSys) attending remotely.

**Comment by marley** [comment]
Sorry, but you've got the wrong Marley!

**Comment by patrickmn** [comment]
Patrick Nielsen, in person

**Comment by jackgavigan** [comment]
Marley Gray is with Microsoft.

**Comment by chaals** [comment]
This issue can be closed (long ago)
